version: '3.8'
services:
  broker:
    image: eclipse-mosquitto
    container_name: broker
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/home/ubuntu/mosquitto/config
      - ./mosquitto/data:/home/ubuntu/mosquitto/data
      - ./mosquitto/log:/home/ubuntu/mosquitto/log